export default (await import('vue')).defineComponent({
    name: "AboutUs"
});
function __VLS_template() {
    let __VLS_ctx;
    /* Components */
    let __VLS_otherComponents;
    let __VLS_own;
    let __VLS_localComponents;
    let __VLS_components;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("bg-primary text-gray-600 body-font") }, id: ("about"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("max-w-screen-xl container mx-auto flex px-4 py-24 md:flex-row flex-col items-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("lg:flex-grow w-full md:w-1/2 lg:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h1, __VLS_intrinsicElements.h1)({ ...{ class: ("font-merriweather text-[42px] md:text-[56px] lg:text-[56px] text-secondary mb-4 w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("font-montserrat text-[16px] md:text-[16px] lg:text-[18px] text-paragraphs mb-8 leading-relaxed w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("w-full md:w-1/2 lg:w-1/2 flex justify-center md:justify-end lg:justify-end") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("object-cover h-[250px] w-full md:h-[300px] md:w-[380px] lg:h-[300px] lg:w-[380px] object-center rounded-2xl shadow-2xl") }, alt: ("Vianočné osvetlenie"), src: ("./img/about.png"), });
    if (typeof __VLS_styleScopedClasses === 'object' && !Array.isArray(__VLS_styleScopedClasses)) {
        __VLS_styleScopedClasses['bg-primary'];
        __VLS_styleScopedClasses['text-gray-600'];
        __VLS_styleScopedClasses['body-font'];
        __VLS_styleScopedClasses['max-w-screen-xl'];
        __VLS_styleScopedClasses['container'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-24'];
        __VLS_styleScopedClasses['md:flex-row'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['lg:flex-grow'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['md:w-1/2'];
        __VLS_styleScopedClasses['lg:w-1/2'];
        __VLS_styleScopedClasses['lg:pr-24'];
        __VLS_styleScopedClasses['md:pr-16'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['md:items-start'];
        __VLS_styleScopedClasses['md:text-left'];
        __VLS_styleScopedClasses['mb-16'];
        __VLS_styleScopedClasses['md:mb-0'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['font-merriweather'];
        __VLS_styleScopedClasses['text-[42px]'];
        __VLS_styleScopedClasses['md:text-[56px]'];
        __VLS_styleScopedClasses['lg:text-[56px]'];
        __VLS_styleScopedClasses['text-secondary'];
        __VLS_styleScopedClasses['mb-4'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['font-montserrat'];
        __VLS_styleScopedClasses['text-[16px]'];
        __VLS_styleScopedClasses['md:text-[16px]'];
        __VLS_styleScopedClasses['lg:text-[18px]'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['mb-8'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['md:w-1/2'];
        __VLS_styleScopedClasses['lg:w-1/2'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['justify-center'];
        __VLS_styleScopedClasses['md:justify-end'];
        __VLS_styleScopedClasses['lg:justify-end'];
        __VLS_styleScopedClasses['object-cover'];
        __VLS_styleScopedClasses['h-[250px]'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['md:h-[300px]'];
        __VLS_styleScopedClasses['md:w-[380px]'];
        __VLS_styleScopedClasses['lg:h-[300px]'];
        __VLS_styleScopedClasses['lg:w-[380px]'];
        __VLS_styleScopedClasses['object-center'];
        __VLS_styleScopedClasses['rounded-2xl'];
        __VLS_styleScopedClasses['shadow-2xl'];
    }
    var __VLS_slots;
    return __VLS_slots;
    const __VLS_componentsOption = {};
    const __VLS_name = "AboutUs";
    let __VLS_internalComponent;
}
