export default (await import('vue')).defineComponent({
    name: "Contact"
});
function __VLS_template() {
    let __VLS_ctx;
    /* Components */
    let __VLS_otherComponents;
    let __VLS_own;
    let __VLS_localComponents;
    let __VLS_components;
    let __VLS_styleScopedClasses;
    // CSS variable injection 
    // CSS variable injection end 
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("text-gray-600 body-font relative bg-primary") }, id: ("contact"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container px-5 py-24 mx-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col text-center w-full mb-12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h1, __VLS_intrinsicElements.h1)({ ...{ class: ("sm:text-3xl text-2xl font-medium title-font  text-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("lg:w-2/3 mx-auto leading-relaxed text-base text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("lg:w-1/2 md:w-2/3 mx-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-wrap -m-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-2 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)({ for: ("name"), ...{ class: ("leading-7 text-sm text-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input, __VLS_intrinsicElements.input)({ type: ("text"), id: ("name"), name: ("name"), ...{ class: ("w-full bg-paragraphs rounded border border-secondary focus:border-paragraphs focus:bg-secondary focus:ring-2 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-2 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)({ for: ("email"), ...{ class: ("leading-7 text-sm text-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input, __VLS_intrinsicElements.input)({ type: ("email"), id: ("email"), name: ("email"), ...{ class: ("w-full bg-paragraphs rounded border border-secondary focus:border-paragraphs focus:bg-secondary focus:ring-2 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-2 w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)({ for: ("message"), ...{ class: ("leading-7 text-sm text-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.textarea, __VLS_intrinsicElements.textarea)({ id: ("message"), name: ("message"), ...{ class: ("w-full bg-paragraphs rounded border border-secondary focus:border-paragraphs focus:bg-secondary focus:ring-2 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-8 transition-colors duration-200 ease-in-out") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-2 w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("flex mx-auto text-paragraphs bg-secondary border-0 py-3 px-14 focus:outline-none hover:bg-indigo-600 rounded-lg text-lg") }, });
    if (typeof __VLS_styleScopedClasses === 'object' && !Array.isArray(__VLS_styleScopedClasses)) {
        __VLS_styleScopedClasses['text-gray-600'];
        __VLS_styleScopedClasses['body-font'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['bg-primary'];
        __VLS_styleScopedClasses['container'];
        __VLS_styleScopedClasses['px-5'];
        __VLS_styleScopedClasses['py-24'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['mb-12'];
        __VLS_styleScopedClasses['sm:text-3xl'];
        __VLS_styleScopedClasses['text-2xl'];
        __VLS_styleScopedClasses['font-medium'];
        __VLS_styleScopedClasses['title-font'];
        __VLS_styleScopedClasses['text-secondary'];
        __VLS_styleScopedClasses['lg:w-2/3'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['text-base'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['lg:w-1/2'];
        __VLS_styleScopedClasses['md:w-2/3'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['-m-2'];
        __VLS_styleScopedClasses['p-2'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['leading-7'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['text-secondary'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['bg-paragraphs'];
        __VLS_styleScopedClasses['rounded'];
        __VLS_styleScopedClasses['border'];
        __VLS_styleScopedClasses['border-secondary'];
        __VLS_styleScopedClasses['focus:border-paragraphs'];
        __VLS_styleScopedClasses['focus:bg-secondary'];
        __VLS_styleScopedClasses['focus:ring-2'];
        __VLS_styleScopedClasses['text-base'];
        __VLS_styleScopedClasses['outline-none'];
        __VLS_styleScopedClasses['text-gray-700'];
        __VLS_styleScopedClasses['py-1'];
        __VLS_styleScopedClasses['px-3'];
        __VLS_styleScopedClasses['leading-8'];
        __VLS_styleScopedClasses['transition-colors'];
        __VLS_styleScopedClasses['duration-200'];
        __VLS_styleScopedClasses['ease-in-out'];
        __VLS_styleScopedClasses['p-2'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['leading-7'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['text-secondary'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['bg-paragraphs'];
        __VLS_styleScopedClasses['rounded'];
        __VLS_styleScopedClasses['border'];
        __VLS_styleScopedClasses['border-secondary'];
        __VLS_styleScopedClasses['focus:border-paragraphs'];
        __VLS_styleScopedClasses['focus:bg-secondary'];
        __VLS_styleScopedClasses['focus:ring-2'];
        __VLS_styleScopedClasses['text-base'];
        __VLS_styleScopedClasses['outline-none'];
        __VLS_styleScopedClasses['text-gray-700'];
        __VLS_styleScopedClasses['py-1'];
        __VLS_styleScopedClasses['px-3'];
        __VLS_styleScopedClasses['leading-8'];
        __VLS_styleScopedClasses['transition-colors'];
        __VLS_styleScopedClasses['duration-200'];
        __VLS_styleScopedClasses['ease-in-out'];
        __VLS_styleScopedClasses['p-2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['relative'];
        __VLS_styleScopedClasses['leading-7'];
        __VLS_styleScopedClasses['text-sm'];
        __VLS_styleScopedClasses['text-secondary'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['bg-paragraphs'];
        __VLS_styleScopedClasses['rounded'];
        __VLS_styleScopedClasses['border'];
        __VLS_styleScopedClasses['border-secondary'];
        __VLS_styleScopedClasses['focus:border-paragraphs'];
        __VLS_styleScopedClasses['focus:bg-secondary'];
        __VLS_styleScopedClasses['focus:ring-2'];
        __VLS_styleScopedClasses['h-32'];
        __VLS_styleScopedClasses['text-base'];
        __VLS_styleScopedClasses['outline-none'];
        __VLS_styleScopedClasses['text-gray-700'];
        __VLS_styleScopedClasses['py-1'];
        __VLS_styleScopedClasses['px-3'];
        __VLS_styleScopedClasses['resize-none'];
        __VLS_styleScopedClasses['leading-8'];
        __VLS_styleScopedClasses['transition-colors'];
        __VLS_styleScopedClasses['duration-200'];
        __VLS_styleScopedClasses['ease-in-out'];
        __VLS_styleScopedClasses['p-2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['bg-secondary'];
        __VLS_styleScopedClasses['border-0'];
        __VLS_styleScopedClasses['py-3'];
        __VLS_styleScopedClasses['px-14'];
        __VLS_styleScopedClasses['focus:outline-none'];
        __VLS_styleScopedClasses['hover:bg-indigo-600'];
        __VLS_styleScopedClasses['rounded-lg'];
        __VLS_styleScopedClasses['text-lg'];
    }
    var __VLS_slots;
    return __VLS_slots;
    const __VLS_componentsOption = {};
    const __VLS_name = "Contact";
    let __VLS_internalComponent;
}
