export default (await import('vue')).defineComponent({
    name: "Footer"
});
function __VLS_template() {
    let __VLS_ctx;
    /* Components */
    let __VLS_otherComponents;
    let __VLS_own;
    let __VLS_localComponents;
    let __VLS_components;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.footer, __VLS_intrinsicElements.footer)({ ...{ class: ("text-gray-600 bg-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("max-w-screen-xl container px-5 py-24 mx-auto flex md:items-start lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ ...{ class: ("flex md:justify-start justify-center md:pt-4 lg:pt-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ ...{ class: ("md:h-[50px] lg:h-[50px] h-[35px]") }, src: ("./img/logo_tmavy.png"), alt: (""), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex-grow flex flex-wrap md:pl-20 -mb-10 md:mt-0 mt-10 md:text-left text-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col md:items-start lg:items-start items-center lg:w-1/3 md:w-1/2 w-full px-4 p-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("font-montserrat-semibold text-[18px] md:text-[24px] lg:text-[24px] text-headings tracking-widest mb-3 text-primary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("font-montserrat text-[14px] md:text-[18px] lg:text-[18px] text-[#E8D7A0]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col md:items-start lg:items-start items-center lg:w-1/3 md:w-1/2 w-full px-4 p-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("font-montserrat-semibold text-[18px] md:text-[24px] lg:text-[24px] text-headings tracking-widest mb-3 text-primary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("font-montserrat text-[14px] md:text-[18px] lg:text-[18px] text-[#E8D7A0]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col md:items-start lg:items-start items-center lg:w-1/3 md:w-1/2 w-full px-4 p-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("font-montserrat-semibold text-[18px] md:text-[24px] lg:text-[24px] text-headings tracking-widest mb-3 text-primary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("font-montserrat text-[14px] md:text-[18px] lg:text-[18px] text-[#E8D7A0]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ href: ("mailto:obchod@uniled.sk"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("bg-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container mx-auto py-6 px-5 flex flex-wrap flex-col sm:flex-row justify-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("font-montserrat-semibold text-[12px] md:text-[16px] lg:text-[16px] text-primary text-center") }, });
    if (typeof __VLS_styleScopedClasses === 'object' && !Array.isArray(__VLS_styleScopedClasses)) {
        __VLS_styleScopedClasses['text-gray-600'];
        __VLS_styleScopedClasses['bg-secondary'];
        __VLS_styleScopedClasses['max-w-screen-xl'];
        __VLS_styleScopedClasses['container'];
        __VLS_styleScopedClasses['px-5'];
        __VLS_styleScopedClasses['py-24'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['md:items-start'];
        __VLS_styleScopedClasses['lg:items-start'];
        __VLS_styleScopedClasses['md:flex-row'];
        __VLS_styleScopedClasses['md:flex-nowrap'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['w-64'];
        __VLS_styleScopedClasses['flex-shrink-0'];
        __VLS_styleScopedClasses['md:mx-0'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['md:text-left'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['md:justify-start'];
        __VLS_styleScopedClasses['justify-center'];
        __VLS_styleScopedClasses['md:pt-4'];
        __VLS_styleScopedClasses['lg:pt-4'];
        __VLS_styleScopedClasses['md:h-[50px]'];
        __VLS_styleScopedClasses['lg:h-[50px]'];
        __VLS_styleScopedClasses['h-[35px]'];
        __VLS_styleScopedClasses['flex-grow'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['md:pl-20'];
        __VLS_styleScopedClasses['-mb-10'];
        __VLS_styleScopedClasses['md:mt-0'];
        __VLS_styleScopedClasses['mt-10'];
        __VLS_styleScopedClasses['md:text-left'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['md:items-start'];
        __VLS_styleScopedClasses['lg:items-start'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['lg:w-1/3'];
        __VLS_styleScopedClasses['md:w-1/2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['font-montserrat-semibold'];
        __VLS_styleScopedClasses['text-[18px]'];
        __VLS_styleScopedClasses['md:text-[24px]'];
        __VLS_styleScopedClasses['lg:text-[24px]'];
        __VLS_styleScopedClasses['text-headings'];
        __VLS_styleScopedClasses['tracking-widest'];
        __VLS_styleScopedClasses['mb-3'];
        __VLS_styleScopedClasses['text-primary'];
        __VLS_styleScopedClasses['font-montserrat'];
        __VLS_styleScopedClasses['text-[14px]'];
        __VLS_styleScopedClasses['md:text-[18px]'];
        __VLS_styleScopedClasses['lg:text-[18px]'];
        __VLS_styleScopedClasses['text-[#E8D7A0]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['md:items-start'];
        __VLS_styleScopedClasses['lg:items-start'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['lg:w-1/3'];
        __VLS_styleScopedClasses['md:w-1/2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['font-montserrat-semibold'];
        __VLS_styleScopedClasses['text-[18px]'];
        __VLS_styleScopedClasses['md:text-[24px]'];
        __VLS_styleScopedClasses['lg:text-[24px]'];
        __VLS_styleScopedClasses['text-headings'];
        __VLS_styleScopedClasses['tracking-widest'];
        __VLS_styleScopedClasses['mb-3'];
        __VLS_styleScopedClasses['text-primary'];
        __VLS_styleScopedClasses['font-montserrat'];
        __VLS_styleScopedClasses['text-[14px]'];
        __VLS_styleScopedClasses['md:text-[18px]'];
        __VLS_styleScopedClasses['lg:text-[18px]'];
        __VLS_styleScopedClasses['text-[#E8D7A0]'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['md:items-start'];
        __VLS_styleScopedClasses['lg:items-start'];
        __VLS_styleScopedClasses['items-center'];
        __VLS_styleScopedClasses['lg:w-1/3'];
        __VLS_styleScopedClasses['md:w-1/2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['font-montserrat-semibold'];
        __VLS_styleScopedClasses['text-[18px]'];
        __VLS_styleScopedClasses['md:text-[24px]'];
        __VLS_styleScopedClasses['lg:text-[24px]'];
        __VLS_styleScopedClasses['text-headings'];
        __VLS_styleScopedClasses['tracking-widest'];
        __VLS_styleScopedClasses['mb-3'];
        __VLS_styleScopedClasses['text-primary'];
        __VLS_styleScopedClasses['font-montserrat'];
        __VLS_styleScopedClasses['text-[14px]'];
        __VLS_styleScopedClasses['md:text-[18px]'];
        __VLS_styleScopedClasses['lg:text-[18px]'];
        __VLS_styleScopedClasses['text-[#E8D7A0]'];
        __VLS_styleScopedClasses['bg-paragraphs'];
        __VLS_styleScopedClasses['container'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['py-6'];
        __VLS_styleScopedClasses['px-5'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['sm:flex-row'];
        __VLS_styleScopedClasses['justify-center'];
        __VLS_styleScopedClasses['font-montserrat-semibold'];
        __VLS_styleScopedClasses['text-[12px]'];
        __VLS_styleScopedClasses['md:text-[16px]'];
        __VLS_styleScopedClasses['lg:text-[16px]'];
        __VLS_styleScopedClasses['text-primary'];
        __VLS_styleScopedClasses['text-center'];
    }
    var __VLS_slots;
    return __VLS_slots;
    const __VLS_componentsOption = {};
    const __VLS_name = "Footer";
    let __VLS_internalComponent;
}
