export default (await import('vue')).defineComponent({
    name: "Gallery"
});
function __VLS_template() {
    let __VLS_ctx;
    /* Components */
    let __VLS_otherComponents;
    let __VLS_own;
    let __VLS_localComponents;
    let __VLS_components;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("text-gray-600 body-font bg-primary") }, id: ("gallery"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("max-w-screen-xl container py-24 mx-auto flex flex-wrap px-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col text-center w-full mb-12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h1, __VLS_intrinsicElements.h1)({ ...{ class: ("sm:text-3xl text-2xl font-medium title-font  text-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("lg:w-2/3 mx-auto leading-relaxed text-base text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-wrap flex-col md:flex-row lg:flex-row md:-m-2 -m-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-wrap w-full md:w-1/2 lg:w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("md:p-2 p-1 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ alt: ("gallery"), ...{ class: ("w-full object-cover h-full object-center block rounded-2xl") }, src: ("https://dummyimage.com/500x300"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("md:p-2 p-1 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ alt: ("gallery"), ...{ class: ("w-full object-cover h-full object-center block rounded-2xl") }, src: ("https://dummyimage.com/501x301"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("md:p-2 p-1 w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ alt: ("gallery"), ...{ class: ("w-full h-full object-cover object-center block rounded-2xl") }, src: ("https://dummyimage.com/600x360"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-wrap w-full md:w-1/2 lg:w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("md:p-2 p-1 w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ alt: ("gallery"), ...{ class: ("w-full h-full object-cover object-center block rounded-2xl") }, src: ("https://dummyimage.com/601x361"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("md:p-2 p-1 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ alt: ("gallery"), ...{ class: ("w-full object-cover h-full object-center block rounded-2xl") }, src: ("https://dummyimage.com/502x302"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("md:p-2 p-1 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ alt: ("gallery"), ...{ class: ("w-full object-cover h-full object-center block rounded-2xl") }, src: ("https://dummyimage.com/503x303"), });
    if (typeof __VLS_styleScopedClasses === 'object' && !Array.isArray(__VLS_styleScopedClasses)) {
        __VLS_styleScopedClasses['text-gray-600'];
        __VLS_styleScopedClasses['body-font'];
        __VLS_styleScopedClasses['bg-primary'];
        __VLS_styleScopedClasses['max-w-screen-xl'];
        __VLS_styleScopedClasses['container'];
        __VLS_styleScopedClasses['py-24'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['mb-12'];
        __VLS_styleScopedClasses['sm:text-3xl'];
        __VLS_styleScopedClasses['text-2xl'];
        __VLS_styleScopedClasses['font-medium'];
        __VLS_styleScopedClasses['title-font'];
        __VLS_styleScopedClasses['text-secondary'];
        __VLS_styleScopedClasses['lg:w-2/3'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['text-base'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['md:flex-row'];
        __VLS_styleScopedClasses['lg:flex-row'];
        __VLS_styleScopedClasses['md:-m-2'];
        __VLS_styleScopedClasses['-m-1'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['md:w-1/2'];
        __VLS_styleScopedClasses['lg:w-1/2'];
        __VLS_styleScopedClasses['md:p-2'];
        __VLS_styleScopedClasses['p-1'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['object-cover'];
        __VLS_styleScopedClasses['h-full'];
        __VLS_styleScopedClasses['object-center'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['rounded-2xl'];
        __VLS_styleScopedClasses['md:p-2'];
        __VLS_styleScopedClasses['p-1'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['object-cover'];
        __VLS_styleScopedClasses['h-full'];
        __VLS_styleScopedClasses['object-center'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['rounded-2xl'];
        __VLS_styleScopedClasses['md:p-2'];
        __VLS_styleScopedClasses['p-1'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['h-full'];
        __VLS_styleScopedClasses['object-cover'];
        __VLS_styleScopedClasses['object-center'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['rounded-2xl'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['md:w-1/2'];
        __VLS_styleScopedClasses['lg:w-1/2'];
        __VLS_styleScopedClasses['md:p-2'];
        __VLS_styleScopedClasses['p-1'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['h-full'];
        __VLS_styleScopedClasses['object-cover'];
        __VLS_styleScopedClasses['object-center'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['rounded-2xl'];
        __VLS_styleScopedClasses['md:p-2'];
        __VLS_styleScopedClasses['p-1'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['object-cover'];
        __VLS_styleScopedClasses['h-full'];
        __VLS_styleScopedClasses['object-center'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['rounded-2xl'];
        __VLS_styleScopedClasses['md:p-2'];
        __VLS_styleScopedClasses['p-1'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['object-cover'];
        __VLS_styleScopedClasses['h-full'];
        __VLS_styleScopedClasses['object-center'];
        __VLS_styleScopedClasses['block'];
        __VLS_styleScopedClasses['rounded-2xl'];
    }
    var __VLS_slots;
    return __VLS_slots;
    const __VLS_componentsOption = {};
    const __VLS_name = "Gallery";
    let __VLS_internalComponent;
}
