export default (await import('vue')).defineComponent({
    name: "Services"
});
function __VLS_template() {
    let __VLS_ctx;
    /* Components */
    let __VLS_otherComponents;
    let __VLS_own;
    let __VLS_localComponents;
    let __VLS_components;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("text-gray-600 body-font bg-primary") }, id: ("services"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("max-w-screen-xl container mx-auto py-20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col text-center w-full mb-16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h1, __VLS_intrinsicElements.h1)({ ...{ class: ("sm:text-3xl text-2xl font-medium title-font  text-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-wrap text-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-4 lg:w-1/6 md:w-1/3 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("border-2 border-paragraphs px-4 py-6 rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("./img/design.png"), alt: (""), ...{ class: ("w-[60px] h-[60px] inline-block") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("leading-relaxed mt-4 text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-4 lg:w-1/6 md:w-1/3 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("border-2 border-paragraphs px-4 py-6 rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("./img/project_management.png"), alt: (""), ...{ class: ("w-[60px] h-[60px] inline-block") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("leading-relaxed mt-4 text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-4 lg:w-1/6 md:w-1/3 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("border-2 border-paragraphs px-4 py-6 rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("./img/manufactury.png"), alt: (""), ...{ class: ("w-[60px] h-[60px] inline-block") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("leading-relaxed mt-4 text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-4 lg:w-1/6 md:w-1/3 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("border-2 border-paragraphs px-4 py-6 rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("./img/instalation.png"), alt: (""), ...{ class: ("w-[60px] h-[60px] inline-block") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("leading-relaxed mt-4 text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-4 lg:w-1/6 md:w-1/3 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("border-2 border-paragraphs px-4 py-6 rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("./img/warehouse.png"), alt: (""), ...{ class: ("w-[60px] h-[60px] inline-block") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("leading-relaxed mt-4 text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("p-4 lg:w-1/6 md:w-1/3 w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("border-2 border-paragraphs px-4 py-6 rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("./img/maintenance.png"), alt: (""), ...{ class: ("w-[60px] h-[60px] inline-block") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("leading-relaxed mt-4 text-paragraphs") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    if (typeof __VLS_styleScopedClasses === 'object' && !Array.isArray(__VLS_styleScopedClasses)) {
        __VLS_styleScopedClasses['text-gray-600'];
        __VLS_styleScopedClasses['body-font'];
        __VLS_styleScopedClasses['bg-primary'];
        __VLS_styleScopedClasses['max-w-screen-xl'];
        __VLS_styleScopedClasses['container'];
        __VLS_styleScopedClasses['mx-auto'];
        __VLS_styleScopedClasses['py-20'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-col'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['w-full'];
        __VLS_styleScopedClasses['mb-16'];
        __VLS_styleScopedClasses['sm:text-3xl'];
        __VLS_styleScopedClasses['text-2xl'];
        __VLS_styleScopedClasses['font-medium'];
        __VLS_styleScopedClasses['title-font'];
        __VLS_styleScopedClasses['text-secondary'];
        __VLS_styleScopedClasses['flex'];
        __VLS_styleScopedClasses['flex-wrap'];
        __VLS_styleScopedClasses['text-center'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['lg:w-1/6'];
        __VLS_styleScopedClasses['md:w-1/3'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['border-2'];
        __VLS_styleScopedClasses['border-paragraphs'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-6'];
        __VLS_styleScopedClasses['rounded-lg'];
        __VLS_styleScopedClasses['w-[60px]'];
        __VLS_styleScopedClasses['h-[60px]'];
        __VLS_styleScopedClasses['inline-block'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['mt-4'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['lg:w-1/6'];
        __VLS_styleScopedClasses['md:w-1/3'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['border-2'];
        __VLS_styleScopedClasses['border-paragraphs'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-6'];
        __VLS_styleScopedClasses['rounded-lg'];
        __VLS_styleScopedClasses['w-[60px]'];
        __VLS_styleScopedClasses['h-[60px]'];
        __VLS_styleScopedClasses['inline-block'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['mt-4'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['lg:w-1/6'];
        __VLS_styleScopedClasses['md:w-1/3'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['border-2'];
        __VLS_styleScopedClasses['border-paragraphs'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-6'];
        __VLS_styleScopedClasses['rounded-lg'];
        __VLS_styleScopedClasses['w-[60px]'];
        __VLS_styleScopedClasses['h-[60px]'];
        __VLS_styleScopedClasses['inline-block'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['mt-4'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['lg:w-1/6'];
        __VLS_styleScopedClasses['md:w-1/3'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['border-2'];
        __VLS_styleScopedClasses['border-paragraphs'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-6'];
        __VLS_styleScopedClasses['rounded-lg'];
        __VLS_styleScopedClasses['w-[60px]'];
        __VLS_styleScopedClasses['h-[60px]'];
        __VLS_styleScopedClasses['inline-block'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['mt-4'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['lg:w-1/6'];
        __VLS_styleScopedClasses['md:w-1/3'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['border-2'];
        __VLS_styleScopedClasses['border-paragraphs'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-6'];
        __VLS_styleScopedClasses['rounded-lg'];
        __VLS_styleScopedClasses['w-[60px]'];
        __VLS_styleScopedClasses['h-[60px]'];
        __VLS_styleScopedClasses['inline-block'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['mt-4'];
        __VLS_styleScopedClasses['text-paragraphs'];
        __VLS_styleScopedClasses['p-4'];
        __VLS_styleScopedClasses['lg:w-1/6'];
        __VLS_styleScopedClasses['md:w-1/3'];
        __VLS_styleScopedClasses['w-1/2'];
        __VLS_styleScopedClasses['border-2'];
        __VLS_styleScopedClasses['border-paragraphs'];
        __VLS_styleScopedClasses['px-4'];
        __VLS_styleScopedClasses['py-6'];
        __VLS_styleScopedClasses['rounded-lg'];
        __VLS_styleScopedClasses['w-[60px]'];
        __VLS_styleScopedClasses['h-[60px]'];
        __VLS_styleScopedClasses['inline-block'];
        __VLS_styleScopedClasses['leading-relaxed'];
        __VLS_styleScopedClasses['mt-4'];
        __VLS_styleScopedClasses['text-paragraphs'];
    }
    var __VLS_slots;
    return __VLS_slots;
    const __VLS_componentsOption = {};
    const __VLS_name = "Services";
    let __VLS_internalComponent;
}
